### ISSUE TITLE
catalog mark fields - autoselect inclusion=automatic

### ISSUE THREAD

**Issue by ghost** [leo-schick/mara-singer#6]
currently only selected fields are added to the catalog selection.

I align with [singer-discover](https://github.com/chrisgoddard/singer-discover), set `"selected": true` as well for all meta fields where `inclusion` is `automatic` (see [singer-io doc. metadata](https://github.com/singer-io/getting-started/blob/master/docs/DISCOVERY_MODE.md#metadata]))

**Comment by hz-lschick** [comment]
This has been implemented in branch v0.8.0
